name: brick_breaker
description: "Re-implementing Woz's Breakout game in Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flame: ^1.11.0
  flutter:
    sdk: flutter
  flutter_animate:
  google_fonts:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
